### ISSUE TITLE
Integration into official TREZOR Firmare

### ISSUE THREAD

**Issue by prusnak** [NoodleDoodleNoodleDoodleNoodleDoodleNoo/trezor-xmr#3]
Here is the list of steps that needs to be done in order to get Monero into the official TREZOR firmware:

- [ ] 0. provide instructions how to build current implementation of trezor-xmr TREZOR firmware
- [ ] 1. add necessary protobuf messages to trezor-common
- [ ] 2. add monero calls to trezorctl
- [ ] 3. add cryptocode to trezor-crypto (if needed)
- [ ] 4. add functionality to trezor-mcu

**Comment by sir-lebowski** [comment]
The dude abides.

**Comment by dternyak** [comment]
@NoodleDoodleNoodleDoodleNoodleDoodleNoo Check out [this](https://github.com/NoodleDoodleNoodleDoodleNoodleDoodleNoo/trezor-xmr/issues/3) reddit post - the community seems willing to fund a proposal if necessary.

**Comment by prusnak** [comment]
Honestly, I don't care about one-time bounties, because they don't
motivate developers to create code of high quality that could be merged
into upstream development and maintained further there. Like could have
been seen exactly in this example. What I care about are developers who
are willing to dedicate their time to maintain their code, so we won't
run into unresolvable issues later, that could be fixed only by removing
this feature.

**Comment by NoodleDoodleNoodleDoodleNoodleDoodleNoo** [comment]
Honestly, I don't care about pricks working for commercial entities as well. Which is why people are free to pull or contribute to this project *if* they want or *if* they feel like they need to. I don't care about merging upstream as well, others can just do it themselves if they feel like it.

**Comment by prusnak** [comment]
This might come as a surprise to you, but AFAIK you took a bounty and
thus you are a "commercial entity prick" as well.

Also I am glad you confirm my words that your intent was never to create
something that will become a part of the official firmware.

**Comment by NoodleDoodleNoodleDoodleNoodleDoodleNoo** [comment]
There was no bounty. Get your fact straight. Whatever the community "donated" it was done AFTER the experimental firmware releases were done. I neither asked for it, my "work" was all voluntary. 

Right, this is what I "created". I'll do whatever I want with it. You are free to spend your life being a prick, as am I free to do whatever I want. Funny how that works.

**Comment by prusnak** [comment]
Sorry, I thought you claimed the bounty. Hopefully someone will use it
to do the proper integration.

**Comment by prusnak** [comment]
Closing the issue as there is obviously no interest from your side.

**Comment by tikwanleap** [comment]
prusnak, you should be grateful that NoodleDoodle freely developed this code to integrate XMR in Trezor. Since you will be potentially profiting off this enhancement, your company should be responsible for integrating and maintaining this code in your product.

It's rather offensive to me that you are implying that if people don't continue maintaining this code for your  benefit, that you would rather just remove the support for XMR.
